### ISSUE TITLE
Persistent Meta Data Storage

### ISSUE THREAD

**Issue by Silthus** [art-framework/art-framework#7]
All ART objects need a way to store persistent data about their execution. This could be in NBT, flatfiles or a database.

- [x] **Actions**: Persist execute once actions, cooldowns, etc.
- [x] **Requirements**: store counter, reset timer and more
- [x] **Trigger**: Persist execute once trigger, cooldowns, etc.
- [x] Hibernate database integration provider

The storage provider should be changeable by the server owner and invisible to the actual ART objects. If no provider is configured a fallback to an in memory provider should occur.
